all:
  vars:
    # Proxmox host for disk passthrough configuration
    proxmox_host: pve01
  children:
    proxmox:
      hosts:
        pve01:
          ansible_host: 192.168.0.26
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    storage:
      hosts:
        storage-lxc:
          ansible_host: 192.168.0.101
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    media:
      hosts:
        media-stack:
          ansible_host: 192.168.0.100
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          storage_server: 192.168.0.101
    proxies:
      hosts:
        traefik-lxc:
          ansible_host: 192.168.0.254
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
