---
# Site playbook - runs both storage and docker-services in order
- import_playbook: proxmox.yml # noqa: name[play]
- import_playbook: storage.yml # noqa: name[play]
- import_playbook: traefik.yml # noqa: name[play]
- import_playbook: monitoring.yml # noqa: name[play]
- import_playbook: docker-services.yml # noqa: name[play]
